path_classifiers:
  test:
    - "tests/*"
  docs:
    - README.md
    - LICENSE.txt

extraction:
  python:
    prepare:
      packages: numpy
  cpp:
    prepare:
      packages:
        - g++-6 python
        - git cmake swig
        - libgsl-dev libfftw3-dev pkg-config
        - libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev
    after_prepare:
      - mkdir -p $LGTM_WORKSPACE/bin
      - mkdir -p $LGTM_WORKSPACE/include
      - mkdir -p $LGTM_WORKSPACE/lib
      - ln -s /usr/bin/g++-6 $LGTM_WORKSPACE/bin/g++
      - ln -s /usr/bin/gcc-6 $LGTM_WORKSPACE/bin/gcc
      - export PATH=$LGTM_WORKSPACE/latest-gcc-symlinks:$PATH
    configure:
      - mkdir $LGTM_SRC/build && cd $LGTM_SRC/build
      - cmake ..

    index:
      build_command:
        - make
